[Splash Theme]
# Name of this theme
name=Default
# Timeout (in ms) after which the next logo image appears, or 0 to indicate
# that the image switches when the next app is started
timeout=0
# List of logos (comma separated)
imagelist=logo.png
# preview image
preview=preview.png
# short description
info=Nice splash screen showing\nthe XFce logo
# Author
author=Francois Le Clainche\n<fleclainche@wanadoo.fr>
