#!/bin/sh
#
#  xfce4
#
#  Copyright (C) 2011 Guido Berhoerster (guido+xfce.org@berhoerster.name)
#  Copyright (C) 2015, 2018 Simon Steinbeiß (simon@xfce.org)
#  Copyright (C) 2011, 2022 Jarno Suni (8@iki.fi)
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#

lockdir=/tmp/xflock4-lock
if ! mkdir "$lockdir" 2>/dev/null; then
    >&2 printf '%s\n' 'Error: xflock4 running already'
    exit 1
fi
trap 'rm -rf "$lockdir"; trap - EXIT' HUP INT TERM EXIT

# Wait a bit so that user have time to raise finger from a key if
# the script is run in terminal.
[ -t 0 ] && sleep 1

# Use a custom lock command, if given.
LOCK_CMD=$(xfconf-query -c xfce4-session -p /general/LockCommand || :)
[ -n "$LOCK_CMD" ] && {
    exit_code=0
    /bin/sh -c "$LOCK_CMD" && exit || {
        exit_code=$?
        >&2 printf "'%s' exited with status %d\n" "$LOCK_CMD" $exit_code
        exit $exit_code
    }
}

# Else try certain screensavers for locking.
for lock_cmd in \
    xscreensaver \
    xfce4-screensaver
do
    # To redirect stdin to /dev/null is needed at least for xscreensaver
    # to not have 1 s delay when invoked on terminal.
    ${lock_cmd}-command --lock </dev/null 2>/dev/null && exit
done

# Else access locking failed.
exit 1
